require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'spec/spec_helper.rb'
   - 'spec/rails_helper.rb'
   - 'spec/support/**/*'
   - 'config/**/*'
   - '**/Rakefile'
   - '**/Gemfile'

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  AllowURI: true

Layout/FirstParameterIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/SignalException:
  EnforcedStyle: semantic

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/MultilineBlockChain:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
